version: '3.9'

services:
  web:
    build: .
    command: gunicorn wielandtech.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=wielandtechdb
      - DB_USER=wielanduser
      - DB_PASSWORD=yourpassword
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wielandtechdb
      - POSTGRES_USER=wielanduser
      - POSTGRES_PASSWORD=yourpassword

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
