version: '3.9'

services:
  web:
    build: .
    command: gunicorn wielandtech.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      REDIS_IP: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: 0
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost', 8000))" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  backup:
    image: postgres:16-alpine
    depends_on:
      - db
    environment:
      # these are read by pg_dump/psql at runtime:
      PGPASSWORD: ${DATABASE_PASSWORD}
      PGUSER: ${DATABASE_USER}
      PGDATABASE: ${DATABASE_NAME}
    volumes:
      - ./db_backups:/backups
    restart: "no"
    entrypoint: >
      sh -c "
        # timestamp
        TS=\$(date +'%Y%m%d_%H%M%S') &&
        # single-line pg_dump invocation
        pg_dump \
          -h db \
          -U \"\$PGUSER\" \
          -d \"\$PGDATABASE\" \
          --format=custom \
          -f /backups/\"\$PGDATABASE\"_\"\$TS\".dump
      "
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/maintenance.html:/var/www/html/maintenance.html
      - ./nginx:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
